;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cmt Ara 30 2023
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STACK SEGMENT PARA STACK 'STACK'
      DW 20 DUP(?)
STACK ENDS

DATA SEGMENT PARA 'DATA'

SAYII1 DB  21D,18D,15D,12D,10D,7D,5D,3D,2D,1D,0D,0D,0D,0D,1D,2D,4D,6D,8D,11D,13D,16D,19D,22D,26D
SAYII2 DB  29D,32D,35D,38D,40D,43D,45D,46D,48D,49D,49D,49D,49D,49D,48D,46D,45D,43D,40D,38D,35D,32D,29D,25D,22D

DATA ENDS
CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STACK

START PROC FAR
        MOV AX, DATA
	MOV DS, AX
	
	MOV DX, 62H
	MOV AL, 00H	

ENDLESS:
        XOR SI,SI
L0:
        MOV AL, SAYII1[SI]

	INC SI	
	OUT DX, AL
        CALL DELAY
        CMP SI, 25D
        JB L0
	
	XOR SI, SI
	
L1:     MOV AL, SAYII2[SI]

        INC SI
	OUT DX, AL
	CALL DELAY
	CMP SI, 25D
        JB L1

        JMP ENDLESS
START ENDP


DELAY PROC NEAR 
      PUSH CX
      MOV CX, 25H
L1:   LOOP L1
      POP CX
      RET
DELAY ENDP


CODE    ENDS
        END START